name: mgw_tutorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure this matches your Flutter SDK constraints

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For localization
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.8 # Check for latest version
  provider: ^6.1.2 # Check for latest version
  intl: ^0.20.2   # Check for latest version
  flutter_secure_storage: ^9.0.0
  # Networking & Storage
  http: ^1.2.1 # Check for latest version
  shared_preferences: ^2.2.3 # Check for latest version

  # Device & System Interaction
  image_picker: ^1.1.1 # Check for latest version
  device_info_plus: ^10.1.0 # Check for latest version
  url_launcher: ^6.2.6 # Check for latest version
  share_plus: ^7.0.0 # Check for latest version
  http_parser: ^4.0.2 # Check for latest version
  
  youtube_explode_dart: ^2.3.4 # Check for latest version
  dio: ^5.4.3+1                # Check for latest version
  path_provider: ^2.1.3        # Check for latest version
  sqflite: ^2.3.0
  permission_handler: ^11.3.1  # For storage permissions if needed
  open_filex: ^4.4.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5 
  flutter_pdfview: ^1.4.0
  webview_flutter: ^4.9.0
  connectivity_plus: ^6.1.4
  youtube_player_iframe: ^5.2.1 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Check for latest version (e.g., ^3.0.0 or ^4.0.0)

# ==================================================
# FLUTTER SECTION - Pay close attention to indentation (2 spaces)
# ==================================================
flutter:
  uses-material-design: true
  generate: true # This enables flutter gen-l10n

  # ------------------- ASSETS DECLARATION -------------------
  # This tells Flutter to include the contents of the assets/fonts/ directory.
  # If you have other assets (like images), add their directories here too.
  # Example:
  # assets:
  #   - assets/images/
  #   - assets/fonts/
  assets:
    - assets/fonts/ # This makes all files in assets/fonts/ available

  # ------------------- FONTS DECLARATION --------------------
  # This declares the NotoSansEthiopic font family and points to the
  # NotoSansEthiopic-Regular.ttf file as its primary (and only, in this scenario) asset.
  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-Regular.ttf
          # You can optionally specify weight 400, but it's the default if it's the only one.
          # weight: 400
# ==================================================
# END OF FLUTTER SECTION
# ==================================================

# flutter_gen configuration (if you use it for more than l10n).
# For standard l10n, `generate: true` above and your l10n.yaml are primary.
flutter_gen:
  synthetic-package: false




